---
settings:
  name: BlueXP
  platform: cloud
  search: bluexp-relnotes,bluexp-setup-admin,bluexp-cloud-volumes-ontap,bluexp-ontap-onprem,bluexp-azure-netapp-files,bluexp-fsx-ontap,bluexp-cloud-volumes-service-gcp,bluexp-kubernetes,bluexp-remediation,bluexp-backup-recovery,bluexp-copy-sync,bluexp-classification,bluexp-tiering,bluexp-replication,bluexp-edge-caching,bluexp-cloud-ops,bluexp-automation,cloud-volumes-ontap-relnotes,bluexp-storagegrid,bluexp-e-series,bluexp-s3-storage,bluexp-economic-efficiency,bluexp-operational-resiliency,bluexp-digital-wallet,bluexp-blob-storage,bluexp-reports,bluexp-volume-caching,bluexp-disaster-recovery
  internal:
    pdf_enabled: false
    lipi_enabled: true
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Alle BlueXP-Dokumentationen
    url: "/index.html"
product-family:
  sidebarlinks:
  - title: Alle
    tags: all
    class: active
  - title: API
    tags: api
  - title: Anschlüsse und Konten
    tags: admin
  - title: Erweiterungen
    tags: extension
  - title: Governance
    tags: governance
  - title: Systemzustand
    tags: health
  - title: Mobilität
    tags: mobility
  - title: Darstellt
    tags: protection
  - title: Storage
    tags: storage
  tiles:
  - title: Willkommen bei BlueXP
    icon: "./media/icon-docs.png"
    url: concept-overview.html
    summary: Erfahren Sie mehr über die Einführung von BlueXP.
    tags: all
  - title: Einrichtung und Administration
    icon: "./media/icon-admin.png"
    url: https://docs.netapp.com/us-en/bluexp-setup-admin/index.html
    summary: Erfahren Sie, wie Sie mit BlueXP beginnen und Connectors, Konten und
      vieles mehr verwalten.
    tags: all,admin
  - title: Versionshinweise
    icon: "./media/icon-docs.png"
    url: https://docs.netapp.com/us-en/bluexp-relnotes/index.html
    summary: Erfahren Sie, was in BlueXP neu ist.
    tags: all
  - title: Amazon FSX für NetApp ONTAP
    icon: "./media/icon-fsx.png"
    url: https://docs.netapp.com/us-en/bluexp-fsx-ontap/index.html
    summary: Alle Funktionen von ONTAP als nativen, von AWS gemanagten Service nutzen
    tags: all,storage,aws
  - title: Amazon S3 Storage
    icon: "./media/icon-s3.png"
    url: https://docs.netapp.com/us-en/bluexp-s3-storage/index.html
    summary: Erkennung und Management von Amazon S3 Buckets in Ihren AWS-Konten
    tags: all,storage,aws
  - title: API
    icon: "./media/icon-api.png"
    url: https://docs.netapp.com/us-en/bluexp-automation/index.html
    summary: Programmgesteuertes Verwalten Ihrer Cloud-basierten Ressourcen
    tags: all,api
  - title: Automatisierungsskatalog
    icon: "./media/icon-api.png"
    url: https://docs.netapp.com/us-en/netapp-automation/solutions/bac-overview.html
    summary: Verwenden Sie skriptbasierte Lösungen, um die Implementierung und Integration
      von NetApp Produkten und Services zu automatisieren.
    tags: all,governance
  - title: Azure Blob Storage
    icon: "./media/icon-azure-blob.png"
    url: https://docs.netapp.com/us-en/bluexp-blob-storage/index.html
    summary: Erkennung und Management von Azure Blob Storage in Ihren Azure-Abonnements
    tags: all,storage
  - title: Azure NetApp Dateien
    icon: "./media/icon-anf.png"
    url: https://docs.netapp.com/us-en/bluexp-azure-netapp-files/index.html
    summary: Der hochperformante File-Storage-Service für Ihre wichtigsten Business-Applikationen.
    tags: all,storage,azure
  - title: Backup und Recovery (Cloud-Backup)
    icon: "./media/icon-backup.png"
    url: https://docs.netapp.com/us-en/bluexp-backup-recovery/index.html
    summary: Backup und Restore von Cloud- und On-Premises-Daten
    tags: all,aws,azure,gcp,protection
  - title: Klassifizierung (Cloud Data Sense)
    icon: "./media/icon-data-sense.png"
    url: https://docs.netapp.com/us-en/bluexp-classification/index.html
    summary: Sorgen Sie für den Schutz Ihrer Applikationsdaten und Cloud-Umgebungen.
    tags: all,governance,aws,azure,gcp
  - title: Cloud-Betrieb (Computing)
    icon: "./media/icon-compute.png"
    url: https://docs.netapp.com/us-en/bluexp-cloud-ops/index.html
    summary: Erhalten Sie einen transparenten Überblick über Ihre Cloud-Computing-Ausgaben
      und lassen Sie potenzielle Einsparungen erkennen.
    tags: all,aws,extension
  - title: Cloud Volumes ONTAP
    icon: "./media/icon-cvo.png"
    url: https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/index.html
    summary: Machen Sie Ihren Cloud-Storage erschwinglicher, intelligenter, konform
      und sicher.
    tags: all,storage,aws,azure,gcp
  - title: Cloud Volumes Service für Google Cloud
    icon: "./media/icon-cvs.png"
    url: https://docs.netapp.com/us-en/bluexp-cloud-volumes-service-gcp/index.html
    summary: Sichern, schützen und beschleunigen Sie Ihren File Storage.
    tags: all,storage,gcp
  - title: Kopieren und Synchronisieren (Cloud Sync)
    icon: "./media/icon-sync.png"
    url: https://docs.netapp.com/us-en/bluexp-copy-sync/index.html
    summary: Datensynchronisierung von On-Premises- und Cloud-Datenspeichern
    tags: all,aws,azure,gcp,mobility
  - title: Digitaler Berater (Active IQ)
    icon: "./media/icon-activeiq.png"
    url: https://docs.netapp.com/us-en/active-iq/index.html
    tags: all,health
    summary: Sofort anwendbare, informative Details für optimalen Storage-Zustand
  - title: Digitale Brieftasche
    icon: "./media/digital-wallet.png"
    url: https://docs.netapp.com/us-en/bluexp-digital-wallet/index.html
    tags: all,governance
    summary: Verwalten und überwachen Sie Ihre Lizenzen und Abonnements.
  - title: Disaster Recovery
    icon: "./media/icon-disaster-recovery.png"
    url: https://docs.netapp.com/us-en/bluexp-disaster-recovery/index.html
    tags: all,protection
    summary: Schützen Sie lokale VMware-Workloads mit VMware Cloud on Amazon FSX for
      ONTAP als Disaster-Recovery-Standort.
  - title: E-Series Systeme
    icon: "./media/icon-e-series.png"
    url: https://docs.netapp.com/us-en/bluexp-e-series/index.html
    summary: Entdecken Sie E-Series Systeme, mit denen Sie alle Daten in Ihrer gesamten
      Hybrid-Multi-Cloud anzeigen können.
    tags: all,storage
  - title: Wirtschaftliche Effizienz
    icon: "./media/icon-economic-efficiency.png"
    url: https://docs.netapp.com/us-en/bluexp-economic-efficiency/index.html
    summary: Identifizieren Sie Cluster mit aktueller oder prognostizierter niedriger
      Kapazität und implementieren Sie Daten-Tiering oder zusätzliche Kapazitätsempfehlungen.
    tags: all,governance
  - title: Edge Caching (Global File Cache)
    icon: "./media/icon-cache.png"
    url: https://docs.netapp.com/us-en/bluexp-edge-caching/index.html
    summary: Globale Dateifreigabe in Echtzeit für Ihre Mitarbeiter an verschiedenen
      Standorten
    tags: all,mobility,aws,azure,gcp
  - title: Google Cloud Storage
    icon: "./media/icon-google-cloud-storage.png"
    url: https://docs.netapp.com/us-en/bluexp-google-cloud-storage/index.html
    summary: Erkennen und managen Sie die Cloud Storage Buckets in Ihrem Google Konto.
    tags: all,storage
  - title: Kubernetes-Cluster
    icon: "./media/icon-kubernetes.png"
    url: https://docs.netapp.com/us-en/bluexp-kubernetes/index.html
    summary: Erweitertes Datenmanagement der Kubernetes-Cluster in der Hybrid Cloud
      –
    tags: all,storage,aws,azure
  - title: Migrationsberichte
    icon: "./media/icon-reports.png"
    url: https://docs.netapp.com/us-en/bluexp-reports/index.html
    summary: Ermitteln Sie die Anzahl der Dateien, die Tiefe und Breite der Dateisystemstrukturen,
      die größten Dateien und vieles mehr in Ihrer Speicherlandschaft.
    tags: all,storage
  - title: On-Premises ONTAP Cluster
    icon: "./media/icon-onprem.png"
    url: https://docs.netapp.com/us-en/bluexp-ontap-onprem/index.html
    summary: Managen Sie Ihre NetApp AFF- und FAS-Systeme über BlueXP mit den Datenservices
      von System Manager und BlueXP.
    tags: all,storage
  - title: Operative Ausfallsicherheit
    icon: "./media/icon-op-resiliency.png"
    url: https://docs.netapp.com/us-en/bluexp-operational-resiliency/index.html
    summary: Implementieren Sie automatische Risikobehebungen für Firmware- und Software-Konfigurationen,
      um den Zustand der ONTAP-Cluster aufrechtzuerhalten.
    tags: all,health
  - title: Korrektur (AppTemplate)
    icon: "./media/icon-app-template.png"
    url: https://docs.netapp.com/us-en/bluexp-remediation/index.html
    summary: Automatisieren Sie Aktionen in BlueXP, um die Bereitstellung zu beschleunigen
      und manuelle Arbeiten zu vermeiden.
    tags: all,health
  - title: Replizierung
    icon: "./media/icon-replication.png"
    url: https://docs.netapp.com/us-en/bluexp-replication/index.html
    summary: Replizieren Sie Daten zwischen Storage-Systemen, um Backup und Disaster
      Recovery zu unterstützen.
    tags: all,protection
  - title: StorageGRID
    icon: "./media/icon-storagegrid.png"
    url: https://docs.netapp.com/us-en/bluexp-storagegrid/index.html
    summary: Erkennung und Management Ihrer StorageGRID Systeme
    tags: all,storage
  - title: Dashboard zur Nachhaltigkeit
    icon: "./media/icon-sustainability.png"
    url: https://docs.netapp.com/us-en/active-iq/learn_BlueXP_sustainability.html
    summary: Analysieren Sie die Nachhaltigkeit Ihrer Storage-Systeme
    tags: all,governance
  - title: Tiering (Cloud Tiering)
    icon: "./media/icon-tiering.png"
    url: https://docs.netapp.com/us-en/bluexp-tiering/index.html
    summary: Erweitern Sie Ihren lokalen ONTAP-Storage in die Cloud.
    tags: all,aws,azure,gcp,mobility
  - title: Volume-Caching
    icon: "./media/icon-volume-caching.png"
    url: https://docs.netapp.com/us-en/bluexp-volume-caching/index.html
    summary: Erstellen Sie ein schreibbares Cache-Volume, um den Zugriff auf Daten
      zu beschleunigen oder den Datenverkehr von Volumes zu reduzieren, auf die sehr
      viel zugegriffen wird.
    tags: all,mobility
